# Generated by Django 3.0.6 on 2020-05-29 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perum', '0003_remove_pelanggan_no_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelanggan',
            name='no_unit',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
