# Generated by Django 3.0.6 on 2020-05-29 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('perum', '0004_pelanggan_no_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelanggan',
            name='no_unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='perum.Unit'),
        ),
    ]
