# Generated by Django 3.0.6 on 2020-05-30 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perum', '0008_auto_20200530_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelanggan',
            name='nama',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
