# Generated by Django 3.0.6 on 2020-05-30 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perum', '0009_auto_20200530_1312'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pelanggan',
        ),
    ]
