# Generated by Django 3.0.6 on 2020-05-30 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('perum', '0010_delete_pelanggan'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pelanggan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255, null=True)),
                ('no_telp', models.CharField(max_length=15, null=True)),
                ('email', models.CharField(max_length=200, null=True)),
                ('id_administrasi', models.IntegerField(null=True)),
                ('no_unit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='perum.Unit')),
            ],
        ),
    ]
