# Generated by Django 3.0.6 on 2020-05-30 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perum', '0011_pelanggan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pelanggan',
            name='no_unit',
        ),
    ]
