# Generated by Django 3.0.6 on 2020-05-30 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perum', '0012_remove_pelanggan_no_unit'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pelanggan',
        ),
    ]
