# Generated by Django 3.0.6 on 2020-06-02 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perum', '0017_administrasi'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelanggan',
            name='administrasi',
            field=models.ManyToManyField(to='perum.Administrasi'),
        ),
    ]
