# Generated by Django 3.0.6 on 2020-06-02 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perum', '0018_pelanggan_administrasi'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrasi',
            name='angsuran_ke',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], max_length=255, null=True),
        ),
    ]
