# Generated by Django 3.0.6 on 2020-06-02 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('perum', '0019_administrasi_angsuran_ke'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pelanggan',
            name='administrasi',
        ),
        migrations.AddField(
            model_name='administrasi',
            name='pelanggan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='perum.Pelanggan'),
        ),
    ]
