# Generated by Django 3.0.6 on 2020-06-02 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perum', '0021_administrasi_no_unit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='administrasi',
            old_name='pelanggan',
            new_name='nama',
        ),
    ]
