# Generated by Django 3.0.6 on 2020-06-08 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perum', '0022_auto_20200602_2205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unit',
            name='foto_rumah',
        ),
        migrations.AlterField(
            model_name='administrasi',
            name='status_bayar',
            field=models.CharField(choices=[('Lunas', 'Lunas'), ('Belum Bayar', 'Belum Bayar')], default='Lunas', max_length=255, null=True),
        ),
    ]
