# Generated by Django 3.0.6 on 2020-06-08 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('perum', '0025_harga'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrasi',
            name='angsuran_ke',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='harga',
            name='harga_unit',
            field=models.IntegerField(null=True),
        ),
        migrations.CreateModel(
            name='Angsuran',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uang_muka', models.IntegerField(null=True)),
                ('lama_angsur', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=255, null=True)),
                ('harga_unit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='perum.Harga')),
                ('nama', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='perum.Pelanggan')),
            ],
        ),
    ]
