# Generated by Django 3.0.6 on 2020-06-08 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('perum', '0026_auto_20200608_1907'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='angsuran',
            name='harga_unit',
        ),
        migrations.AddField(
            model_name='angsuran',
            name='no_unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='perum.Unit'),
        ),
    ]
