# Generated by Django 3.0.6 on 2020-06-08 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perum', '0028_auto_20200608_1918'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='angsuran',
            name='harga_unit',
        ),
    ]
