# Generated by Django 3.0.6 on 2020-06-16 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perum', '0031_pelanggan_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pelanggan',
            name='user',
        ),
    ]
