# Generated by Django 3.0.6 on 2020-06-16 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perum', '0034_remove_pelanggan_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='status_rumah',
            field=models.CharField(choices=[('Tersedia', 'Tersedia'), ('Tidak Tersedia', 'Tidak Tersedia'), ('Dipesan', 'Dipesan')], max_length=200, null=True),
        ),
    ]
