# Generated by Django 3.0.6 on 2020-06-16 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perum', '0035_auto_20200616_2114'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='tanggal',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
