# Generated by Django 3.0.6 on 2020-06-24 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('perum', '0038_auto_20200624_1749'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipe_unit', models.IntegerField(max_length=5, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='unit',
            name='tipe_unit',
        ),
        migrations.AddField(
            model_name='unit',
            name='tipe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='perum.Tipe'),
        ),
    ]
