# Generated by Django 3.0.6 on 2020-06-24 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perum', '0039_auto_20200624_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipe',
            name='tipe_unit',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
